### ISSUE TITLE
minor bug: replace the GA code with the variable

### ISSUE THREAD

**Issue by newgene** [biothings/biothings_sites#1]
The GA code on [this line](https://github.com/biothings/biothings_sites/blame/893308d355116dd97d27c677677902406d457b0e/mygene-theme/main.html#L95) should be replaced by the variable `{{ga_tracking}}`.  Probably does not affect our tracking, but need to be fixed.

Same for the main.html file in other themes.

**Comment by marcodarko** [comment]
Updated it! working fine 👍
